### PR TITLE
Pnext adaptation

### PR DESCRIPTION
**Pull request by Mnosek**
Pull request for #42

### CODE REVIEW

**Comment by Mnosek** [comment]
cc @warpech @miyconst

**Comment by warpech** [comment]
LGTM. @miyconst WDYT about including PropertyMetadata classes directly in the project?

**Comment by miyconst** [comment]
>@miyconst WDYT about including PropertyMetadata classes directly in the project?

Looks to be the best possible solution for now, but let's keep in mind that UserAdmin has to be remade from scratch.

**Comment by Mnosek** [comment]
Ok guys, thanks for a review.

**Pull request merged**
