### PR TITLE
added SignOut after reset user's password

### PR DESCRIPTION
**Pull request by diliger**
#27

### CODE REVIEW

**Comment by un-tone** [comment]
Shouldn't we add the similar code in the `ResetPasswordPage.Handle(Input.Save)` method?

**Comment by warpech** [comment]
Ping @diliger. I totally agree with @un-tone.

**Comment by warpech** [comment]
@un-tone I guess it will be faster if you take over finishing of this PR, would you agree?

**Comment by un-tone** [comment]
@warpech agree

**Comment by warpech** [comment]
Great, please proceed

**Comment by un-tone** [comment]
Finished. Please review.

**Pull request merged**
